<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="Constraints" nsURI="Constraints" nsPrefix="constraints">
  <eAnnotations references="Slingshot.repository#_Gan2ABWpEe-DGZvw9jQajw">
    <details key="return" value="responseTime"/>
  </eAnnotations>
  <eAnnotations references="Slingshot.system#_1YAgMClJEe-lBN28kF6cQP">
    <details key="Source:In" value="x.numberOfUsers > 0 &amp;&amp; x.numberOfUsers &lt; 2147483647"/>
    <details key="Target:In" value="x.numberOfUsers > 0"/>
    <details key="Source:Out" value="x.responseTime > 1.0"/>
    <details key="Target:Out" value="x.responseTime > 1.0"/>
  </eAnnotations>
  <eAnnotations references="Slingshot.system#_0s6UwClJEe-lBN28kF6cQQ">
    <details key="Source:Out" value="x.method == &quot;asdf&quot;"/>
    <details key="Target:In" value="x.method == &quot;asdf&quot;"/>
    <details key="Source:Out:Delayed"/>
  </eAnnotations>
  <eAnnotations references="Slingshot.system#_Ph2DwBWqEe-DGZvw9jQajw">
    <details key="Source:Out" value="x.resourceDemand > 1.0"/>
    <details key="Target:In" value="x.resourceDemand > 1.0"/>
    <details key="Target:Out" value="x.utilization > 1.0"/>
    <details key="Source:In" value="x.utilization > 1.0"/>
    <details key="Target:Out:Delayed"/>
  </eAnnotations>
  <eAnnotations references="Slingshot.system#_LZc80OkmEe-YvM3YpQ3veQ">
    <details key="Source:Out" value="x.active == true &amp;&amp; x.passive == false"/>
    <details key="Target:In" value="x.active == true"/>
  </eAnnotations>
  <eAnnotations references="Slingshot.system#_YOZqUO0pEe-Xa5stiVZNhg">
    <details key="Target:In" value="x.passive == true"/>
    <details key="Source:Out" value="x.active == false &amp;&amp; x.passive == true"/>
  </eAnnotations>
</ecore:EPackage>
