/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.montiarcandcore.ide;


/**
 * Use this class to register ide components.
 */
public class MontiArcAndCoreIdeModule extends AbstractMontiArcAndCoreIdeModule {
}
