/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.montiarcandcore;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MontiArcAndCoreStandaloneSetup extends MontiArcAndCoreStandaloneSetupGenerated {

	public static void doSetup() {
		new MontiArcAndCoreStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
