/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.montiarcandcore.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MontiArcAndCoreUiModule extends AbstractMontiArcAndCoreUiModule {

	public MontiArcAndCoreUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
