/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.montiarcandcore.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.palladiosimulator.xtext.montiarcandcore.parser.antlr.internal.InternalMontiArcAndCoreParser;
import org.palladiosimulator.xtext.montiarcandcore.services.MontiArcAndCoreGrammarAccess;

public class MontiArcAndCoreParser extends AbstractAntlrParser {

	@Inject
	private MontiArcAndCoreGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMontiArcAndCoreParser createParser(XtextTokenStream stream) {
		return new InternalMontiArcAndCoreParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MontiArcAndCore";
	}

	public MontiArcAndCoreGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MontiArcAndCoreGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
