/*
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.montiarcandcore.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.palladiosimulator.xtext.montiarcandcore.ui.internal.MontiarcandcoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MontiArcAndCoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MontiarcandcoreActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MontiarcandcoreActivator activator = MontiarcandcoreActivator.getInstance();
		return activator != null ? activator.getInjector(MontiarcandcoreActivator.ORG_PALLADIOSIMULATOR_XTEXT_MONTIARCANDCORE_MONTIARCANDCORE) : null;
	}

}
