/**
 * generated by Xtext 2.34.0
 */
package org.palladiosimulator.xtext.montiarcandcore.montiArcAndCore.impl;

import org.eclipse.emf.ecore.EClass;

import org.palladiosimulator.xtext.montiarcandcore.montiArcAndCore.MCArrayType;
import org.palladiosimulator.xtext.montiarcandcore.montiArcAndCore.MontiArcAndCorePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>MC Array Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MCArrayTypeImpl extends TypeImpl implements MCArrayType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MCArrayTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MontiArcAndCorePackage.Literals.MC_ARRAY_TYPE;
  }

} //MCArrayTypeImpl
